name: "Release"

on:
  push:
    branches:
      - feat-db-pools-master
    tags:

jobs:
  build-deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: recursive
        ref: feat-db-pools-master

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: appwrite/cloud
        tags: |
          type=pep440,pattern={{version}},value=${{  github.ref_name }}

    - name: Publish to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          VERSION=${{ steps.meta.outputs.version }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}